export const STRINGS = {
    appName: "Pensión Alimenticia Online",
    home: "Inicio",
    about_us: "Nosotros",
    privacy_policy: "Aviso de privavidad",
    terms_and_conditions: "Términos y condiciones",
    contact: "Contacto",
    follow_us: "Síguenos",
    legal: "Legal",
    start_procedure: "Iniciar procedimiento",
    last_update: "Última actualización",
    registration_form: "Formulario de registro",
    marritage_certificate: "Acta de matrimonio",
    data_of_minors: "Datos de los menores",
    debtors_data: "Datos del deudor",
    choose_document: "Elegir archivo",
    rfc: "RFC",
    curp: "CURP",
    explanation_of_the_situation: "Exposición de la situación",
    payslip: "Recibo de nómina",
    i_have_read_and_agreed_: "He leído y acepto los ",
    and: "y",
    submit: "Enviar",
    birth_certificate_of_minors: "Acta de nacimiento de los menores"
}